name: geo_contacts
description: Um projeto flutter que permite cadastrar contatos e identificar a localização no mapa.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  sqflite:
  path_provider:
  http:
  google_maps_flutter: ^2.2.3
  flutter_config: ^2.0.0
  provider:
  flutter_slidable: ^0.6.0
  location_geocoder: ^1.0.5
  geocoding: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

